# Generated by Django 5.0.14 on 2026-09-08 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_tag",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CAMERA", "Camera"),
                            ("LAPTOP", "Laptop"),
                            ("SENSOR", "Sensor"),
                            ("VEHICLE", "Vehicle"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("CHECKED_OUT", "Checked out"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="AVAILABLE",
                        max_length=16,
                    ),
                ),
                ("purchase_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(db_index=True, max_length=16, unique=True),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CheckOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_out_at", models.DateTimeField(auto_now_add=True)),
                ("due_at", models.DateTimeField()),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("condition_note", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkouts",
                        to="inventory.asset",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkouts",
                        to="inventory.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OverdueNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notice_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to="inventory.checkout",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="checkout",
            index=models.Index(
                fields=["returned_at", "due_at"], name="inventory_c_returne_fa48e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkout",
            index=models.Index(
                fields=["employee", "returned_at"],
                name="inventory_c_employe_13cb21_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="overduenotice",
            constraint=models.UniqueConstraint(
                fields=("checkout", "notice_date"),
                name="unique_notice_per_checkout_per_day",
            ),
        ),
    ]
